name: Daily Commit

on:
  schedule:
    - cron: "0 4 * * *" # Runs every day at 4 AM UTC
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Auto commit
        run: |
          echo "$(date) - Keep the streak alive 💪" >> log.txt
          git config --global user.email "kpemmzy@gmail.com"
          git config --global user.name "kpemmzy"
          git add log.txt
          git commit -m "chore: daily commit"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
